#!/usr/bin/env bash

if [ -n "${WWWUSER}" ]; then
    usermod -u "${WWWUSER}" sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu "${WWWUSER}" "$@"
else
    # Cache config in production.
    if [ "${APP_ENV}" = "production" ]; then
        php artisan config:cache
    fi
    # Migration
    php artisan migrate --force
    # Start supervisord
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
