#!/usr/bin/env bash

if [ ! -z "${WWWUSER}" ]; then
    usermod -u "${WWWUSER}" sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu "${WWWUSER}" "$@"
else
    php artisan migrate
    # If APP_KEY is empty, Generate an app key.
    # TODO: DEBUG: always keygen
    php artisan key:generate
    php artisan config:clear
    # if [ -z "${APP_KEY}" ]; then
    #     php artisan key:generate
    # fi
    # Cache config in production.
    if [ "${APP_ENV}" = "production" ]; then
        php artisan config:cache
    fi
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
