#!/usr/bin/env bash

if [ -n "${WWWUSER}" ]; then
    usermod -u "${WWWUSER}" sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu "${WWWUSER}" "$@"
else
    # For mounting a volume for development.
    find bootstrap/cache -not -name ".gitignore" -exec chown "sail:${WWWGROUP}" {} \;
    find storage -not -name ".gitignore" -exec chown "sail:${WWWGROUP}" {} \;
    # Migration
    php artisan migrate
    # Start supervisord
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
