---
AWSTemplateFormatVersion: "2010-09-09"
Description: ACM

Parameters:
  EnvironmentName:
    Description: Environment name, either dev or prod
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Specify either dev or prod

  Subdomain:
    Type: String
    Description: The subdomain

  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The Route 53 Hosted Zone ID

  HostedZoneName:
    Type: String
    Description: The Amazon Route 53 Hosted Zone Name for the optional load balancer alias record - do not include a period at the end
    Default: ""
    AllowedPattern: "(^$|^((?!-)[A-Za-z0-9-]{1,63}(?<!-)\\.)+[A-Za-z]{2,6}$)" # Allow for a blank or a domain name
    ConstraintDescription: Please enter a valid Route 53 Hosted Zone Name

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub ${Subdomain}.${HostedZoneName}
      DomainValidationOptions:
        - DomainName: !Sub ${Subdomain}.${HostedZoneName}
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  Name:
    Description: ALB Stack Name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-Name

  EnvironmentName:
    Description: Environment Name
    Value: !Ref EnvironmentName
    Export:
      Name: !Sub ${AWS::StackName}-EnvironmentName

  CertificateArn:
    Description: Certificate ARN
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::StackName}-CertificateArn
