---
AWSTemplateFormatVersion: 2010-09-09
Description: Secrets Manager

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name - dev or prod
    Default: dev
    AllowedValues:
      - dev
      - prod
    ConstraintDescription: Specify either dev or prod
  AppKey:
    Type: String
    Description: "env: APP_KEY"
  DatabaseName:
    Type: String
    Description: "env: DB_DATABASE"
  DatabaseUserName:
    Type: String
    Description: "env: DB_USERNAME"

Resources:
  AppKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/ReservationSystemStudies/AppKey
      Description: APP_KEY for ReservationSystemStudies
      SecretString: !Ref AppKey
  DatabaseNameSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/ReservationSystemStudies/DatabaseName
      Description: DB_DATABASE for ReservationSystemStudies
      SecretString: !Ref DatabaseName
  DatabaseUserNameSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/ReservationSystemStudies/DatabaseUserName
      Description: DB_USERNAME for ReservationSystemStudies
      SecretString: !Ref DatabaseUserName
  DatabasePasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/ReservationSystemStudies/DatabasePassword
      Description: DB_PASSWORD for ReservationSystemStudies
      GenerateSecretString:
        PasswordLength: 32
        ExcludeCharacters: "/@\"'\\"

Outputs:
  Name:
    Description: Fargate Stack Name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}-Name
  EnvironmentName:
    Description: Environment Name
    Value: !Ref EnvironmentName
    Export:
      Name: !Sub ${AWS::StackName}-EnvironmentName
  AppKeyName:
    Description: The name of APP_KEY
    Value: !Sub ${EnvironmentName}/ReservationSystemStudies/AppKey
    Export:
      Name: !Sub ${AWS::StackName}-AppKeyName
  AppKeyArn:
    Description: The ARN of APP_KEY
    Value: !Ref AppKeySecret
    Export:
      Name: !Sub ${AWS::StackName}-AppKeyArn
  DatabaseName:
    Description: The name of database
    Value: !Sub ${EnvironmentName}/ReservationSystemStudies/DatabaseName
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseName
  DatabaseNameArn:
    Description: The ARN of database
    Value: !Ref DatabaseNameSecret
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseNameArn
  DatabaseUserName:
    Description: The name of database user
    Value: !Sub ${EnvironmentName}/ReservationSystemStudies/DatabaseUserName
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseUserName
  DatabaseUserNameArn:
    Description: The ARN of database user
    Value: !Ref DatabaseUserNameSecret
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseUserNameArn
  DatabasePassword:
    Description: The name of database password
    Value: !Sub ${EnvironmentName}/ReservationSystemStudies/DatabasePassword
    Export:
      Name: !Sub ${AWS::StackName}-DatabasePassword
  DatabasePasswordArn:
    Description: The ARN of database password
    Value: !Ref DatabasePasswordSecret
    Export:
      Name: !Sub ${AWS::StackName}-DatabasePasswordArn
