name: deploy_service
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'
jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ECR_REGISTRY }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY_NAME }}
        flavor: latest=auto
        tags: type=semver,pattern={{version}}
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./infra/docker/prod/Dockerfile
        build-args: |
          WWWGROUP=${{ secrets.WWWGROUP }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs:
    - build-image
    steps:
    - name: No deployment
      run: echo 'No deployment now'
