name: deployment
on:
  push:
    branches:
    - "main"
    tags:
    - "*"
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          hibara428/reservation_system_studies
        flavor: |
          latest=auto
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/8.1/Dockerfile
        build-args: |
          WWWGROUP=${{ secrets.WWWGROUP }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
