name: deploy_cfn_templates
on:
  push:
    branches:
    - "main"
    paths:
    - "infra/cfn/templates/**"
    tags:
    - "**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Upload templates to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp --recursive --region ap-northeast-1 infra/cfn/templates s3://${{ secrets.S3_BUCKET }}/templates
