name: test
on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to ECR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ECR_REGISTRY }}
    - name: Cache "vendor" directory
      id: cache
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Run "composer install" (if "vendor" is NOT cached)
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install -n --prefer-dist
    - name: Set up .env
      run: php -r "copy('.env.testing', '.env');"
    - name: Change owner for tests
      run: chmod -R 777 storage
    - name: Pull a docker image for dev
      run: docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY_NAME }}:dev
    - name: Up containers
      run: ./vendor/bin/sail up -d
    - name: Execute unit and feature tests
      run: ./vendor/bin/sail test --do-not-cache-result
