name: unit_test
on:
  push:
    branches:
    - "main"
  pull_request:
jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache "vendor" directory
      id: cache
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Run "composer install" (if "vendor" is NOT cached)
      if: steps.cache.outputs.cache-hit != 'true'
      run: composer install -n --prefer-dist
    - name: Set up .env
      run: php -r "copy('.env.testing', '.env');"
    - name: Pull a docker image for dev
      run: docker pull hibara428/reservation_system_studies:dev
    - name: Execute unit and feature tests via PHPUnit with Laravel Sail
      run: ./vendor/bin/sail up -d && ./vendor/bin/sail test
